### ISSUE TITLE
No shape propagator issue

### ISSUE THREAD

**Issue by hansely** [KhronosGroup/NNEF-Tools#96]
While converting a tensorflow-pb model to nnef, I encountered an issue saying 

Error: No shape propagator for LeakyRelu

I used the following command for the conversion:
./nnef_tools/convert.py --input-format tensorflow-pb --output-format nnef --input-model model.pb --output-model ./output.nnef --input-shape="[1, 224, 224, 3]" --io-transformation SMART_NHWC_TO_NCHW

Does this mean that the conversion for LeakyRelu operation is not supported?

**Comment by gyenesvi** [comment]
It was left out accidentally, now it should be working, can you check?

**Comment by hansely** [comment]
Thanks, it converts fine to nnef model.
However, when parsing the model with input name as 

graph network(Graph/Preprocess/Input) -> (output),

I'm getting the following error:
_nnef.Error: Parse error in 'graph.nnef' [3:20] expected token ')', found '/'. 
Does the parser not support input name with '/' in it?

**Comment by gyenesvi** [comment]
Of course it does not support '/' in an identifier, that is illegal in most languages since '/' is a math operator.

**Comment by hansely** [comment]
Yes, that is what I got by using nnef_tools/convert.py

**Comment by hansely** [comment]
Even if I change the input name to Graph_Preprocess_Input, it still throws a following error:

Traceback
...
     input_shape = graph.tensor_shapes[input_tensor.name]
KeyError: 'Graph_Preprocess_Input'

Is it because the name doesn't match the original name before conversion?

**Comment by gyenesvi** [comment]
We have corrected the naming issue, now it should substitute illegal characters with '_'.

However, we don't find the line `input_shape = graph.tensor_shapes[input_tensor.name]`. Is that in the converter code? The `graph` object in the converters don't have a `tensor_shapes` attribute.

**Comment by hansely** [comment]
Oh that was from myself. Now it looks good to me.
Thank you.
